import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'ru' | 'en';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  ru: {
    // Navigation
    'nav.dashboard': 'Дэшборд',
    'nav.architecture': 'Архитектура системы',
    'nav.matrix': 'Товарная матрица',
    'nav.sku-constructor': 'Конструктор SKU',
    'nav.dictionary': 'Справочники',
    'nav.kit-builder': 'Сборка комплектов',
    'nav.media': 'Медиа-менеджер',
    'nav.ai-hub': 'Ассистент AI',
    'nav.analysis': 'Анализ',
    'nav.beta': 'Бета',

    // Header & Layout
    'sidebar.tagline': 'Система продукта',
    'header.search': 'Поиск товаров...',
    'header.notifications': 'Уведомления',
    'header.notifications.mark_read': 'Отметить все как прочитанные',
    'header.notifications.close': 'Закрыть панель',
    'header.notifications.n1_title': 'SKU S19024-K сгенерирован',
    'header.notifications.n1_desc': 'Новый комплект добавлен в товарную матрицу',
    'header.notifications.n1_time': '5 мин назад',
    'header.notifications.n2_title': 'Обновление словаря',
    'header.notifications.n2_desc': 'Добавлен новый цвет: Античный белый (40)',
    'header.notifications.n2_time': '1 час назад',
    'header.notifications.n3_title': 'Анализ архитектуры завершен',
    'header.notifications.n3_desc': 'Все 10 сущностей успешно нормализованы',
    'header.notifications.n3_time': '3 часа назад',
    'header.settings': 'Настройки профиля',
    'header.settings.logout': 'Выйти',
    'header.settings.logout_full': 'Выйти из аккаунта',
    'header.settings.save': 'Сохранить',
    'header.settings.system_params': 'Параметры системы',
    'header.settings.interface_lang': 'Язык интерфейса',
    'header.settings.russian': 'Русский',
    'header.settings.english': 'English',
    'header.settings.theme': 'Тема оформления',
    'header.settings.db_version': 'Версия БД',
    'header.settings.integrations': 'Интеграции',
    'header.dev_mode.tooltip': 'Режим разработчика активен — данные пишутся в PostgreSQL',
    'header.dev_mode.subtitle': 'PostgreSQL',
    'header.dev_mode.session': 'Сессия',
    'settings.work_mode': 'Режим работы',
    'settings.developer_mode': 'Режим разработчика',
    'settings.developer_mode_desc': 'Переключение на PostgreSQL для тестирования против реальной БД. Данные тестовой сессии в браузере сохранятся отдельно.',
    'settings.developer_mode_active': 'Данный переключатель демонстрационный — реальное подключение к PostgreSQL появится в следующем обновлении.',
    'settings.data_management': 'Управление данными',
    'settings.export': 'Экспорт',
    'settings.import': 'Импорт',
    'settings.import_error': 'Ошибка импорта. Проверьте файл.',
    'settings.reset_to_defaults': 'Сбросить к дефолту',
    'settings.reset_confirm': 'Сбросить все данные к дефолтным значениям? Это действие необратимо.',
    'header.team': 'Команда продукта',
    'header.admin': 'Администратор',

    // Dashboard
    'dash.title': 'Дэшборд',
    'dash.subtitle': 'Ключевые метрики и статистика',
    'dash.updated': 'Последнее обновление:',
    'dash.active': 'Активных SKU',
    'dash.kits': 'Комплектов',
    'dash.categories': 'Категорий',
    'dash.catDist': 'Распределение по категориям',
    'dash.powerDist': 'Распределение по мощности',
    'dash.recent': 'Недавние товары',
    'dash.viewAll': 'Смотреть все',
    'dash.supplierDist': 'Распределение по поставщикам',
    'dash.alerts': 'Системные уведомления',
    'dash.items': 'Товары',
    'dash.distTitle': 'Распределение',
    'dash.distPower': 'Мощность',
    'dash.distLength': 'Длина',
    'dash.distColor': 'Цвет',
    'dash.quickActions': 'Быстрые действия',
    'dash.quickAddProduct': 'Создать товар',
    'dash.quickManageDict': 'Управление словарями',
    'dash.quickUploadMedia': 'Загрузить медиа',
    'dash.alert.missing_power': 'У 3 товаров не указана мощность',
    'dash.alert.verify_components': '2 компонента комплектов требуют проверки',
    'dash.alert.template_review': 'Новый шаблон названий готов к ревью',

    // Architecture
    'arch.title': 'Архитектура системы',
    'arch.subtitle': 'Глубокий анализ архитектуры, логики SKU и структуры БД',
    'arch.tab.overview': 'Сводка',
    'arch.tab.sku': 'Логика SKU',
    'arch.tab.naming': 'Логика названий',
    'arch.tab.schema': 'Схема БД',
    'arch.tab.system': 'Системный дизайн',
    'arch.summary.title': 'Сводка архитектурного анализа',
    'arch.summary.entities': 'Сущности',
    'arch.summary.relationships': 'Связи',
    'arch.summary.categories': 'Категории',
    'arch.summary.sku_pattern': 'Паттерн SKU',
    'arch.summary.name_templates': 'Шаблоны названий',
    'arch.summary.validation_rules': 'Правила валидации',
    'arch.summary.normalized_tables': 'Нормализованные таблицы',
    'arch.summary.foreign_keys': 'Внешние ключи',
    'arch.summary.product_types': 'Типы товаров',
    'arch.summary.encoding_segments': 'Сегменты кодирования',
    'arch.summary.auto_generation_rules': 'Правила автогенерации',
    'arch.summary.data_integrity': 'Целостность данных',
    'arch.sku.title': 'Паттерн генерации SKU',
    'arch.sku.rules_title': 'Правила валидации SKU',
    'arch.naming.title': 'Паттерн названий товаров',
    'arch.naming.rules_title': 'Правила названий по категориям',
    'arch.schema.title': 'Связи сущностей БД',
    'arch.schema.relationships_title': 'Связи таблиц',
    'arch.schema.close': 'Закрыть',
    'arch.schema.fields': 'полей',
    'arch.system.frontend_title': 'Фронтенд Архитектура',
    'arch.system.backend_title': 'Бэкенд Архитектура',
    'arch.system.ai_title': 'Дизайн AI-готовой базы знаний',
    'arch.system.vector_embeddings': 'Векторные вложения',
    'arch.system.structured_metadata': 'Структурированные метаданные',
    'arch.system.content_templates': 'Шаблоны контента',
    'arch.system.attribute_graph': 'Граф атрибутов',
    'arch.system.media_analysis': 'Анализ медиа',
    'arch.system.multi_language': 'Мультиязычность',

    // Matrix
    'matrix.title': 'Товарная матрица',
    'matrix.subtitle': 'товаров в каталоге',
    'matrix.export': 'Экспорт',
    'matrix.search': 'Поиск по SKU, названию, модели...',
    'matrix.filters': 'Фильтры',
    'matrix.clear': 'Сбросить все',
    'matrix.cat': 'Категории',
    'matrix.sup': 'Поставщики',
    'matrix.col.sku': 'SKU',
    'matrix.col.product': 'Товар',
    'matrix.col.cat': 'Категория',
    'matrix.col.model': 'Модель',
    'matrix.col.power': 'Мощность',
    'matrix.col.length': 'Длина',
    'matrix.col.color': 'Цвет',
    'matrix.col.sup': 'Поставщик',
    'matrix.showing': 'Показано с',
    'matrix.to': 'по',
    'matrix.of': 'из',
    'matrix.empty': 'Товары не найдены',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.architecture': 'System Architecture',
    'nav.matrix': 'Product Matrix',
    'nav.sku-constructor': 'SKU Constructor',
    'nav.dictionary': 'Dictionaries',
    'nav.kit-builder': 'Kit Builder',
    'nav.media': 'Media Manager',
    'nav.ai-hub': 'AI Assistant',
    'nav.analysis': 'Analysis',
    'nav.beta': 'Beta',

    // Header & Layout
    'sidebar.tagline': 'Product System',
    'header.search': 'Search products...',
    'header.notifications': 'Notifications',
    'header.notifications.mark_read': 'Mark all as read',
    'header.notifications.close': 'Close panel',
    'header.notifications.n1_title': 'SKU S19024-K generated',
    'header.notifications.n1_desc': 'New kit added to product matrix',
    'header.notifications.n1_time': '5 min ago',
    'header.notifications.n2_title': 'Dictionary update',
    'header.notifications.n2_desc': 'New color added: Antique White (40)',
    'header.notifications.n2_time': '1 hour ago',
    'header.notifications.n3_title': 'Architecture analysis complete',
    'header.notifications.n3_desc': 'All 10 entities normalized successfully',
    'header.notifications.n3_time': '3 hours ago',
    'header.settings': 'Profile Settings',
    'header.settings.logout': 'Log out',
    'header.settings.logout_full': 'Log out of account',
    'header.settings.save': 'Save',
    'header.settings.system_params': 'System Parameters',
    'header.settings.interface_lang': 'Interface Language',
    'header.settings.russian': 'Russian',
    'header.settings.english': 'English',
    'header.settings.theme': 'Theme',
    'header.settings.db_version': 'DB Version',
    'header.settings.integrations': 'Integrations',
    'header.dev_mode.tooltip': 'Developer mode active — data is written to PostgreSQL',
    'header.dev_mode.subtitle': 'PostgreSQL',
    'header.dev_mode.session': 'Session',
    'settings.work_mode': 'Work Mode',
    'settings.developer_mode': 'Developer Mode',
    'settings.developer_mode_desc': 'Switch to PostgreSQL for testing against a real DB. Test session data in the browser will be kept separately.',
    'settings.developer_mode_active': 'Active. In this iteration the toggle is demonstrative — actual PostgreSQL connection will appear in the next update.',
    'settings.data_management': 'Data Management',
    'settings.export': 'Export',
    'settings.import': 'Import',
    'settings.import_error': 'Import error. Please check the file.',
    'settings.reset_to_defaults': 'Reset to Defaults',
    'settings.reset_confirm': 'Reset all data to default values? This action cannot be undone.',
    'header.team': 'Product Team',
    'header.admin': 'Administrator',

    // Dashboard
    'dash.title': 'Dashboard',
    'dash.items': 'Items',
    'dash.subtitle': 'Key metrics and statistics',
    'dash.updated': 'Last updated:',
    'dash.active': 'Active SKUs',
    'dash.kits': 'Kit Products',
    'dash.categories': 'Categories',
    'dash.catDist': 'Products by Category',
    'dash.powerDist': 'Power Distribution',
    'dash.recent': 'Recent Products',
    'dash.viewAll': 'View all',
    'dash.supplierDist': 'Supplier Distribution',
    'dash.alerts': 'System Alerts',
    'dash.distTitle': 'Distribution',
    'dash.distPower': 'Power',
    'dash.distLength': 'Length',
    'dash.distColor': 'Color',
    'dash.quickActions': 'Quick Actions',
    'dash.quickAddProduct': 'Create Product',
    'dash.quickManageDict': 'Manage Dictionaries',
    'dash.quickUploadMedia': 'Upload Media',
    'dash.alert.missing_power': '3 products missing power specifications',
    'dash.alert.verify_components': '2 kit components need verification',
    'dash.alert.template_review': 'New naming template ready for review',

    // Architecture
    'arch.title': 'System Architecture',
    'arch.subtitle': 'Deep analysis of product architecture, SKU logic, and database design',
    'arch.tab.overview': 'Overview',
    'arch.tab.sku': 'SKU Logic',
    'arch.tab.naming': 'Naming Logic',
    'arch.tab.schema': 'DB Schema',
    'arch.tab.system': 'System Design',
    'arch.summary.title': 'Architecture Analysis Summary',
    'arch.summary.entities': 'Entities',
    'arch.summary.relationships': 'Relationships',
    'arch.summary.categories': 'Categories',
    'arch.summary.sku_pattern': 'SKU Pattern',
    'arch.summary.name_templates': 'Name Templates',
    'arch.summary.validation_rules': 'Validation Rules',
    'arch.summary.normalized_tables': 'Normalized tables',
    'arch.summary.foreign_keys': 'Foreign key links',
    'arch.summary.product_types': 'Product types',
    'arch.summary.encoding_segments': 'Encoding segments',
    'arch.summary.auto_generation_rules': 'Auto-generation rules',
    'arch.summary.data_integrity': 'Data integrity',
    'arch.sku.title': 'SKU Generation Pattern',
    'arch.sku.rules_title': 'SKU Validation Rules',
    'arch.naming.title': 'Product Naming Pattern',
    'arch.naming.rules_title': 'Naming Rules by Category',
    'arch.schema.title': 'Entity Relationships',
    'arch.schema.relationships_title': 'Relationships',
    'arch.schema.close': 'Close',
    'arch.schema.fields': 'fields',
    'arch.system.frontend_title': 'Frontend Architecture',
    'arch.system.backend_title': 'Backend Architecture',
    'arch.system.ai_title': 'AI-Ready Knowledge Base Design',
    'arch.system.vector_embeddings': 'Vector Embeddings',
    'arch.system.structured_metadata': 'Structured Metadata',
    'arch.system.content_templates': 'Content Templates',
    'arch.system.attribute_graph': 'Attribute Graph',
    'arch.system.media_analysis': 'Media Analysis',
    'arch.system.multi_language': 'Multi-language',

    // Matrix
    'matrix.title': 'Product Matrix',
    'matrix.subtitle': 'products in catalog',
    'matrix.export': 'Export',
    'matrix.search': 'Search by SKU, name, model...',
    'matrix.filters': 'Filters',
    'matrix.clear': 'Clear all',
    'matrix.cat': 'Categories',
    'matrix.sup': 'Suppliers',
    'matrix.col.sku': 'SKU',
    'matrix.col.product': 'Product',
    'matrix.col.cat': 'Category',
    'matrix.col.model': 'Model',
    'matrix.col.power': 'Power',
    'matrix.col.length': 'Length',
    'matrix.col.color': 'Color',
    'matrix.col.sup': 'Supplier',
    'matrix.showing': 'Showing',
    'matrix.to': 'to',
    'matrix.of': 'of',

    // SKU Constructor
    'sku.title': 'SKU Constructor',
    'sku.subtitle': 'Build new product SKUs following the GQbox encoding system',
    'sku.step1': 'Category & Model',
    'sku.step2': 'SKU Base',
    'sku.step3': 'Attributes',
    'sku.step4': 'Variant',
    'sku.step5': 'Generate',
    'sku.prev': 'Previous',
    'sku.next': 'Next',
    'sku.reset': 'Reset',
    'sku.generate': 'Generate',
    'sku.category_label': 'Product Category',
    'sku.model_label': 'Model / Line',
    'sku.base_number_label': 'Base Number (5 digits)',
    'sku.variant_code_label': 'Variant Code',
    'sku.variant_code_hint': 'Model differentiation suffix',
    'sku.length_variant_label': 'Length Variant',
    'sku.length_variant_hint': 'Length override (e.g., -2 for 2m)',
    'sku.is_kit_label': 'This is a Kit / Combo product',
    'sku.preview_label': 'SKU Preview',
    'sku.select_placeholder': '— Select',
    'sku.power_label': 'Power (W)',
    'sku.current_label': 'Current (A)',
    'sku.voltage_label': 'Voltage (V)',
    'sku.connector_female_label': 'Female Connector',
    'sku.connector_male_label': 'Male Connector',
    'sku.protocol_label': 'Charging Protocol',
    'sku.body_material_label': 'Body Material',
    'sku.wire_material_label': 'Wire Material',
    'sku.length_label': 'Length (m)',
    'sku.color_label': 'Color',
    'sku.supplier_label': 'Supplier',
    'sku.generate_hint': 'Click generate to create the SKU and product name',
    'sku.copied': 'Copied',
    'sku.copy': 'Copy',
    'sku.duplicate_warning': 'This SKU already exists in the database',
    'sku.use_suggestion': 'Use available',
    'sku.generated_name_label': 'Product Name',
    'sku.generated_category_label': 'Category',
    'sku.generated_model_label': 'Model',
    'sku.generated_color_label': 'Color',
    'sku.generated_supplier_label': 'Supplier',
    'sku.add_to_matrix': 'Add to Matrix',
    'sku.added_to_matrix': 'Product "{name}" added to matrix!',
    'sku.add_success': 'Product successfully added to matrix',
    'sku.toast_duplicate': 'A product with this SKU already exists!',
    'sku.auto_generated_hint': 'SKU and name auto-generated',

    // Detail Card
    'detail.power': 'Power',
    'detail.current': 'Current',
    'detail.voltage': 'Voltage',
    'detail.length': 'Length',
    'detail.devices': 'Devices',
    'detail.speed': 'Speed',
    'detail.input': 'Input',
    'detail.output': 'Output',
    'detail.protocol': 'Protocol',
    'detail.connection': 'Connection',
    'detail.body': 'Body',
    'detail.wire': 'Wire',
    'detail.media': 'Media',
    'detail.no_media': 'No media',
    'detail.description': 'Description',
    'detail.benefits': 'Key Benefits',
    'detail.tags': 'Tags',
    'detail.marketplaces': 'Marketplaces',
    'detail.listed_as_product': 'Listed as product',
    'detail.included_in_bundles': 'Included in bundles',
    'detail.specifications': 'Specifications',
    'detail.connections': 'Connections',
    'detail.materials': 'Materials',
    'detail.supplier': 'Supplier',

    // Dictionaries
    'dict.title': 'Dictionary Manager',
    'dict.subtitle': 'Manage parameter and code lists',
    'dict.add': 'Add',
    'dict.col.code': 'Code',
    'dict.col.source': 'Name (source)',
    'dict.col.product': 'Name (product)',
    'dict.col.color': 'Color',
    'dict.col.products': 'Products',
    'dict.col.actions': 'Actions',
    'dict.col.category': 'Category',
    'dict.col.preview': 'Preview',
    'dict.col.type': 'Type',
    'dict.col.description': 'Description',
    'dict.col.name': 'Name',
    'dict.form.source': 'Name (source)',
    'dict.form.product': 'Name (product)',
    'dict.form.code_placeholder': 'Unique code',
    'dict.form.source_placeholder': 'Source name (as in dictionary)',
    'dict.form.product_placeholder': 'Product name',
    'dict.add_title': 'Add: ',
    'dict.edit_title': 'Edit: ',
    'dict.cancel': 'Cancel',
    'dict.save': 'Save',
    'dict.toast_added': 'Entry "{name}" successfully added!',
    'dict.toast_duplicate': 'Error: entry with code "{code}" already exists!',
    'dict.toast_source_duplicate': 'Source name "{name}" already exists!',
    'dict.edit': 'Edit',
    'dict.editing': 'Editing...',
    'dict.save_success': 'Entry "{name}" updated!',
    'dict.cancel_edit': 'Cancel',
    'dict.delete_confirm': 'Delete entry "{name}"?',
    'dict.edit_placeholder': 'New value',
    'dict.tab.categories': 'Categories',
    'dict.tab.models': 'Models',
    'dict.tab.colors': 'Colors',
    'dict.tab.suppliers': 'Suppliers',
    'dict.tab.connectors': 'Connectors',
    'dict.tab.protocols': 'Protocols',
    'dict.tab.materials': 'Materials',

    // Kit Builder
    'kit.title': 'Kit Builder',
    'kit.subtitle': 'Compose product bundles and combo sets',
    'kit.config': 'Kit Configuration',
    'kit.name': 'Kit Name',
    'kit.components': 'Components',
    'kit.addProduct': 'Add Product',
    'kit.preview': 'Kit Preview',
    'kit.create': 'Create Kit',
    'kit.decrease': 'Decrease',
    'kit.increase': 'Increase',
    'kit.remove': 'Remove',
    'kit.article': 'Kit Article',
    'kit.article_placeholder': 'Enter article manually',
    'kit.article_exists': 'This article already exists',
    'kit.auto_placeholder': 'Generated automatically',
    'kit.total_power': 'Total Power:',
    'kit.clear': 'Clear',
    'kit.add': 'Add',
    'kit.empty_components': 'No raw materials added yet',
    'kit.min_components': 'Minimum 2 components required to create a kit',
    'kit.one_more_needed': 'Add at least 1 more component',
    'kit.toast_created': 'Kit created successfully!',
    'kit.toast_duplicate': 'A kit with this SKU already exists!',
    'kit.add_success': 'Kit created successfully',
    'kit.saving': 'Saving kit...',
    'kit.saved': 'Kit saved',
    'kit.generated_name': 'Generated Name',
    'kit.components_summary': 'Components Summary',
    'kit.no_components': 'No components',
    'kit.search_categories': 'Search category...',
    'kit.search_products': 'Search products...',
    'kit.select_components': 'Select components',
    'kit.no_categories': 'No categories found',
    'kit.no_products': 'No products found',
    'kit.picker_title': 'Select Component',

    // Media Manager
    'media.title': 'Media Manager',
    'media.subtitle': 'assets',
    'media.images': 'images',
    'media.videos': 'videos',
    'media.upload': 'Upload',
    'media.search': 'Search by filename or SKU...',
    'media.all': 'All',
    'media.selected': 'selected',
    'media.clear': 'Clear',
    'media.col.file': 'File',
    'media.col.type': 'Type',
    'media.col.sku': 'SKU',
    'media.col.size': 'Size',
    'media.col.date': 'Date',
    'media.col.actions': 'Actions',
    'media.photos': 'Photos',
    'media.videos_label': 'Videos',
    'media.image_label': 'Image',
    'media.video_label': 'Video',
    'media.not_found': 'No media files found',
    'media.upload_title': 'Upload Media',
    'media.upload_button': 'Upload Files',
    'media.drop_here': 'Drag & drop files here',
    'media.click_browse': 'or click to browse',
    'media.supported_formats': 'Supports JPG, PNG, MP4 up to 100MB',
    'media.file_name': 'File Name',
    'media.file_name_placeholder': 'e.g., product_photo.jpg',
    'media.sku_link': 'Link to Product SKU',
    'media.sku_link_placeholder': 'e.g., S10002E/01',
    'media.download_selected': 'Download selected',
    'media.delete_selected': 'Delete selected',
    'media.toast.uploaded': 'File uploaded successfully:',
    'media.toast.deleted': 'Files removed:',
    'media.toast.downloading': 'Downloading files:',
    'media.toast.download_item': 'Downloading:',
    'media.toast.deleting_item': 'Deleting:',

    // AI Hub
    'ai.title': 'AI Assistant',
    'ai.subtitle': 'Generate content, analyze data, and automate product workflows',
    'ai.quick': 'Quick Actions',
    'ai.status': 'AI Status',
    'ai.placeholder': 'Type your request...',
    'ai.send': 'Send',
    'ai.copy': 'Copy',
    'ai.copied': 'Copied',
    'ai.disclaimer': 'AI responses are generated for demonstration. Connect to OpenAI/Claude API for production use.',
    'ai.preset1_label': 'Generate Product Description',
    'ai.preset1_prompt': 'Write a compelling product description for a 20W PD wall charger with USB-C output, white color, premium aluminum body',
    'ai.preset2_label': 'Analyze SKU Pattern',
    'ai.preset2_prompt': 'Analyze the SKU pattern S10002E-2/01 and explain each segment',
    'ai.preset3_label': 'Generate Image Prompt',
    'ai.preset3_prompt': 'Create a detailed AI image generation prompt for a product photo of a white wireless charging station',
    'ai.preset4_label': 'Translate to Russian',
    'ai.preset4_prompt': 'Translate this product title to Russian: "Premium Braided USB-C to Lightning Cable, 1m, Black, 20W PD"',
    'ai.welcome': 'Hi! I\'m your GQbox product assistant.\n\nI can help with:\n• Writing or improving product descriptions\n• Translating names and specs\n• Analyzing SKU patterns\n• Generating AI image prompts\n• Answering assortment questions\n\nPick a preset or type your own request.',
    'ai.default_response': 'I\'ve analyzed your request about "{query}". This is a placeholder response — in production, this would connect to your AI model (OpenAI, Claude, or local LLM) via Supabase Edge Functions.',

    // Architecture System Descriptions
    'arch.system.fe_nextjs_desc': 'Server Components for data fetching, Client Components for interactivity',
    'arch.system.fe_shadcn_desc': 'Component library with custom theming for dark premium UI',
    'arch.system.fe_tanstack_desc': 'Server state management with caching and optimistic updates',
    'arch.system.fe_zustand_desc': 'Lightweight client state for UI preferences and filters',
    'arch.system.be_supabase_desc': 'Managed Postgres with real-time subscriptions and RLS',
    'arch.system.be_db_functions_desc': 'PL/pgSQL triggers for SKU auto-generation and name templating',
    'arch.system.be_edge_functions_desc': 'Deno-based serverless for AI content generation and external APIs',
    'arch.system.be_storage_desc': 'Organized media storage with CDN delivery for product images',
    'arch.system.ai_vector_desc': 'Product descriptions and attributes stored as pgvector embeddings for semantic search',
    'arch.system.ai_metadata_desc': 'Every product has normalized JSON-LD schema for AI consumption',
    'arch.system.ai_templates_desc': 'AI prompt templates for generating descriptions, titles, and marketing copy',
    'arch.system.ai_graph_desc': 'Product relationships encoded as graph data for recommendation engines',
    'arch.system.ai_media_desc': 'Computer vision pipeline for auto-tagging product images',
    'arch.system.ai_i18n_desc': 'i18n-ready structure with Russian as primary, English for export',

    // Layout
    'layout.collapse_menu': 'Collapse menu',
    'layout.expand_menu': 'Expand menu',
    'layout.open_menu': 'Open menu',

    // Matrix
    'matrix.exporting': 'Exporting...',
    'matrix.empty': 'No products found',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Default language: Russian
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
